apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hospital
  name: hospital
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hospital
    spec:
      restartPolicy: Always
      containers:
        - image: kostenarov/hospital:hospitalimage
          name: hospital
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hospital
  name: hospital
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hospital
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hospital-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hospital
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75